@evoNaplo_HostAddress = https://localhost:7210

GET {{evoNaplo_HostAddress}}/weatherforecast/
Accept: application/json

###

POST {{evoNaplo_HostAddress}}/api/students
Content-Type: application/json

{
  "name": "Teszt Elek",
  "email": "teszt.elek@teszt.hu"
}

###

GET {{evoNaplo_HostAddress}}/api/students

###

POST {{evoNaplo_HostAddress}}/api/mentors
Content-Type: application/json

{
  "name": "Teszt Mentor",
  "email": "teszt.mentor@teszt.hu"
}

###

GET {{evoNaplo_HostAddress}}/api/mentors

###
