<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Bogus" Version="35.6.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.25" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.25">
      <PrivateAssets>all</PrivateAssets>
    <PackageReference Include="ClosedXML" Version="0.105.0" />
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Services\IMentorService.cs" />
    <Compile Remove="Services\IProjectService.cs" />
    <Compile Remove="Services\IStudentService.cs" />
    <Compile Remove="Services\ITeamService.cs" />
    <Compile Remove="Services\MentorService.cs" />
    <Compile Remove="Services\ProjectService.cs" />
    <Compile Remove="Services\StudentService.cs" />
    <Compile Remove="Services\TeamService.cs" />
  </ItemGroup>

</Project>
