import { readdir, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const root = path.resolve(__dirname, "..")

async function listFiles(relativeDir, extensions) {
  const absDir = path.join(root, relativeDir)
  const entries = await readdir(absDir, { withFileTypes: true })

  return entries
    .filter((entry) => entry.isFile())
    .map((entry) => entry.name)
    .filter((name) => extensions.some((ext) => name.endsWith(ext)))
    .sort((a, b) => a.localeCompare(b))
    .map((name) => `./${path.posix.join(relativeDir, name.replace(/\.(ts|tsx)$/, ""))}`)
}

async function main() {
  const [libEntries, hookEntries, componentEntries] = await Promise.all([
    listFiles("lib", [".ts", ".tsx"]),
    listFiles("hooks", [".ts", ".tsx"]),
    listFiles("components/ui", [".ts", ".tsx"]),
  ])

  const content = [
    "// This file is auto-generated by scripts/generate-index.mjs",
    "// Do not edit manually.",
    "",
    ...libEntries.map((entry) => `export * from "${entry}"`),
    "",
    ...hookEntries.map((entry) => `export * from "${entry}"`),
    "",
    ...componentEntries.map((entry) => `export * from "${entry}"`),
    "",
  ].join("\n")

  await writeFile(path.join(root, "index.ts"), content, "utf8")
}

main().catch((error) => {
  console.error(error)
  process.exit(1)
})
