// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using evoNaplo.Data;

#nullable disable

namespace evoNaplo.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330100115_AttendanceSheetMigration")]
    partial class AttendanceSheetMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MentorTeam", b =>
                {
                    b.Property<string>("MentorsId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("TeamsId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MentorsId", "TeamsId");

                    b.HasIndex("TeamsId");

                    b.ToTable("MentorTeam");
                });

            modelBuilder.Entity("evoNaplo.Models.AttendanceSheet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("LengthOfMeeting")
                        .HasColumnType("time");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("WeeklyMeetingTime")
                        .HasColumnType("datetimeoffset");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("AttendanceSheets");
                });

            modelBuilder.Entity("evoNaplo.Models.Mentor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjecCount")
                        .HasColumnType("int");

                    b.Property<int>("StudentCount")
                        .HasColumnType("int");

                    b.Property<int>("TeamCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Mentors");
                });

            modelBuilder.Entity("evoNaplo.Models.Project", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MentorId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("MentorId");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("evoNaplo.Models.ProjectLink", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LinkType")
                        .HasColumnType("int");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectLinks");
                });

            modelBuilder.Entity("evoNaplo.Models.Student", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AttendanceSheetId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("CurrentSemester")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("HasActiveScholarship")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAppliedForInternship")
                        .HasColumnType("bit");

                    b.Property<bool>("HasAppliedForScholarship")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCurrentlyIntern")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFirstEvoCampusSemester")
                        .HasColumnType("bit");

                    b.Property<bool>("IsWorkingStudent")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalGoals")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ScholarshipDuration")
                        .HasColumnType("datetime2");

                    b.Property<string>("TeamId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UniversityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UniversityProgramme")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("WantsToStayWithCurrentTeam")
                        .HasColumnType("bit");

                    b.Property<DateTime>("WorkingStudentDuration")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AttendanceSheetId");

                    b.HasIndex("TeamId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("evoNaplo.Models.Team", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("MentorTeam", b =>
                {
                    b.HasOne("evoNaplo.Models.Mentor", null)
                        .WithMany()
                        .HasForeignKey("MentorsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("evoNaplo.Models.Team", null)
                        .WithMany()
                        .HasForeignKey("TeamsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("evoNaplo.Models.AttendanceSheet", b =>
                {
                    b.HasOne("evoNaplo.Models.Team", "Team")
                        .WithMany("AttendanceSheets")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("evoNaplo.Models.Project", b =>
                {
                    b.HasOne("evoNaplo.Models.Mentor", null)
                        .WithMany("Projects")
                        .HasForeignKey("MentorId");
                });

            modelBuilder.Entity("evoNaplo.Models.ProjectLink", b =>
                {
                    b.HasOne("evoNaplo.Models.Project", "Project")
                        .WithMany("ProjectLinks")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("evoNaplo.Models.Student", b =>
                {
                    b.HasOne("evoNaplo.Models.AttendanceSheet", null)
                        .WithMany("PresentStudents")
                        .HasForeignKey("AttendanceSheetId");

                    b.HasOne("evoNaplo.Models.Team", "Team")
                        .WithMany("Students")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("evoNaplo.Models.Team", b =>
                {
                    b.HasOne("evoNaplo.Models.Project", "Project")
                        .WithMany("Teams")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("evoNaplo.Models.AttendanceSheet", b =>
                {
                    b.Navigation("PresentStudents");
                });

            modelBuilder.Entity("evoNaplo.Models.Mentor", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("evoNaplo.Models.Project", b =>
                {
                    b.Navigation("ProjectLinks");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("evoNaplo.Models.Team", b =>
                {
                    b.Navigation("AttendanceSheets");

                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
